# Generated by Django 4.2.7 on 2023-11-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_rename_cuatomer_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
    ]
